# This is a config for E2B sandbox template.
# You can use template ID (jbjgdwvfejgvrlu8gstg) or template name (vibe-nextjs-asrar-ahammad-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-asrar-ahammad-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-asrar-ahammad-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-asrar-ahammad-2')

team_id = "ed0644a2-0ac0-4f73-94a5-ba0062c8ad34"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-asrar-ahammad-2"
template_id = "jbjgdwvfejgvrlu8gstg"
